name: webwalkthroughs
favicon: null
layout_spectrum: 0.9000257703009993
typography_spectrum: 0.64151
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fecb00'
    - '#4f2300'
    - '#00adf1'
    - '#737d00'
    - '#fe4f18'
  brandStrength: 0.8062288404908031
  lightness: 0.49903228133916855
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
