name: webwalkthroughs
favicon: null
layout_spectrum: 0.51592
typography_spectrum: 0.64151
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e2e7ed'
    - '#576100'
    - '#000000'
    - '#cfb899'
    - '#201d18'
  brandStrength: 0.5625
  lightness: 0.6875
  saturation: 0.0625
  rhythmicContrast: 0.75
purpose: []
