name: webwalkthroughs
favicon: null
layout_spectrum: 0.9000257703009993
typography_spectrum: 0.7149572318885475
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.8062288404908031
  lightness: 0.49903228133916855
  saturation: 0.6143930729012936
  rhythmicContrast: 0.40657469374127686
purpose: []
